# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c9ce8ad737ecdb68b83cc109e74b4a4181e2687ab674b3fdd2476ec78ee08ca75d4bbed68f830a07393049d473be30282161cdb1df29367f3a84a19dd1d6e9c

test:
  secret_key_base: c23c69656a105996eab79a24c9ae552edcc0ef0b22ab183e2432e144ed667491e7c5f84dadecf32a916057e95458cc36e22a74311a0b37a5838dadf9740f859c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
